name: PR automatic creation
on:
  push:
    branches: 
      - main
jobs: 
  CreatePR:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "Automatic PR demo"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:

            Here comes the description of our PR. 

          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
